# -*- coding: utf-8 -*-
"""AudioIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOYe-zkeAUUlg2X2h6C2_BiQsU4BPEV_
"""

from google.colab import files

# Subir archivos de audio (espera el botón de subida)
uploaded = files.upload()

!pip install librosa

import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial.distance import euclidean

# Cargar audios
audio_guitarra, sr_guitarra = librosa.load('guitarra.wav')
audio_flauta, sr_flauta = librosa.load('flauta.wav')

# Extraer MFCC
mfcc_guitarra = librosa.feature.mfcc(y=audio_guitarra, sr=sr_guitarra, n_mfcc=13)
mfcc_flauta = librosa.feature.mfcc(y=audio_flauta, sr=sr_flauta, n_mfcc=13)

# Calcular la media de cada coeficiente MFCC
mfcc_guitarra_mean = np.mean(mfcc_guitarra, axis=1)
mfcc_flauta_mean = np.mean(mfcc_flauta, axis=1)

# Visualizar MFCC en el tiempo
plt.figure(figsize=(12, 6))

plt.subplot(2, 2, 1)
librosa.display.specshow(mfcc_guitarra, x_axis='time', sr=sr_guitarra)
plt.colorbar()
plt.title('MFCC - Guitarra')

plt.subplot(2, 2, 2)
librosa.display.specshow(mfcc_flauta, x_axis='time', sr=sr_flauta)
plt.colorbar()
plt.title('MFCC - Flauta')

# Graficar los MFCC promedios
plt.subplot(2, 1, 2)
plt.plot(mfcc_guitarra_mean, label='Guitarra (promedio)', marker='o')
plt.plot(mfcc_flauta_mean, label='Flauta (promedio)', marker='s')
plt.title("Comparación de MFCC Promedio")
plt.xlabel("Coeficiente MFCC")
plt.ylabel("Valor")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

# Distancia entre las características
distancia = euclidean(mfcc_guitarra_mean, mfcc_flauta_mean)
print(f"Distancia Euclidiana entre MFCC promedio (Guitarra vs Flauta): {distancia:.2f}")

"""SEGUNDO PUNTO;

"""

from google.colab import files

# Subir archivos de audio (espera el botón de subida)
uploaded = files.upload()

!pip install librosa

import librosa
import numpy as np
import matplotlib.pyplot as plt

# Cargar audio
audio, sr = librosa.load('IA.wav')

# Aplicar ventana para evitar errores por bordes
windowed_audio = audio * np.hanning(len(audio))

# FFT
fft_result = np.fft.fft(windowed_audio)
frequencies = np.fft.fftfreq(len(fft_result), 1/sr)
magnitude = np.abs(fft_result)

# Filtrar solo la mitad positiva del espectro (frecuencias reales)
half_len = len(frequencies) // 2
frequencies = frequencies[:half_len]
magnitude = magnitude[:half_len]

# Graficar con límite en el eje x para mejor interpretación
plt.figure(figsize=(12, 6))
plt.plot(frequencies, magnitude)
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Magnitud')
plt.title('🎙️ Espectro de Frecuencias (0 - 5000 Hz)')
plt.xlim(0, 5000)  # Limitar a 0–5000 Hz
plt.grid(True)

# Líneas guía para referencia de graves y agudos
plt.axvline(x=300, color='blue', linestyle='--', label='Graves ≤ 300 Hz')
plt.axvline(x=2000, color='red', linestyle='--', label='Agudos ≥ 2000 Hz')
plt.legend()
plt.show()