# -*- coding: utf-8 -*-
"""Actividad_Parcial_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeXTTcmO7rmNh5NylrYSSncuhZKp-mmZ
"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Cargar datos
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalizar valores de píxeles a [0, 1]
x_train = x_train.reshape((x_train.shape[0], 28, 28, 1)).astype('float32') / 255
x_test = x_test.reshape((x_test.shape[0], 28, 28, 1)).astype('float32') / 255

# Convertir etiquetas a one-hot
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Entrenar
model.fit(x_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Precisión en test: {test_acc:.4f}")

import matplotlib.pyplot as plt
import numpy as np

# Predecir las clases del set de prueba
predictions = model.predict(x_test)

# Mostrar las primeras 10 imágenes con su etiqueta real y la predicha
for i in range(10):
    plt.imshow(x_test[i].reshape(28, 28), cmap='gray')
    plt.title(f"Real: {np.argmax(y_test[i])}, Predicho: {np.argmax(predictions[i])}")
    plt.axis('off')
    plt.show()

# Importar librerías necesarias
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# ------------------------
# 1. Cargar y filtrar el dataset
# ------------------------

# Cargar el dataset CIFAR-10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Clases seleccionadas: airplane (0), automobile (1), truck (9)
selected_classes = [0, 1, 9]
labels = ['airplane', 'automobile', 'truck']

# Función para filtrar las clases seleccionadas
def filter_classes(x, y, classes):
    idx = np.isin(y, classes).flatten()  # Filtrar las clases seleccionadas
    x_filtered = x[idx]
    y_filtered = y[idx]
    y_mapped = np.array([classes.index(label[0]) for label in y_filtered])  # Mapeo de etiquetas
    return x_filtered, to_categorical(y_mapped, num_classes=3)

# Filtrar las clases en los conjuntos de entrenamiento y prueba
x_train_f, y_train_f = filter_classes(x_train, y_train, selected_classes)
x_test_f, y_test_f = filter_classes(x_test, y_test, selected_classes)

# Normalizar las imágenes
x_train_f = x_train_f.astype('float32') / 255
x_test_f = x_test_f.astype('float32') / 255

# ------------------------
# 2. Data Augmentation
# ------------------------

# Definir el generador de imágenes con augmentación
datagen = ImageDataGenerator(
    rotation_range=15,  # Rotaciones aleatorias
    width_shift_range=0.1,  # Desplazamientos horizontales
    height_shift_range=0.1,  # Desplazamientos verticales
    horizontal_flip=True,  # Volteo horizontal
)

# Ajustar el generador a los datos de entrenamiento
datagen.fit(x_train_f)

# ------------------------
# 3. Crear el modelo
# ------------------------

# Crear un modelo secuencial
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),  # Capa convolucional
    MaxPooling2D((2, 2)),  # Capa de max pooling
    Conv2D(64, (3, 3), activation='relu'),  # Otra capa convolucional
    MaxPooling2D((2, 2)),  # Otra capa de max pooling
    Flatten(),  # Aplanar la salida para pasarla a la capa densa
    Dense(64, activation='relu'),  # Capa densa con 64 neuronas
    Dense(3, activation='softmax')  # Capa de salida con 3 clases
])

# ------------------------
# 4. Compilar y entrenar el modelo
# ------------------------

# Compilar el modelo con el optimizador 'adam' y la función de pérdida 'categorical_crossentropy'
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Entrenar el modelo con augmentación de datos
model.fit(datagen.flow(x_train_f, y_train_f, batch_size=64),
          steps_per_epoch=len(x_train_f) // 64,
          epochs=15,
          validation_data=(x_test_f, y_test_f))

# ------------------------
# 5. Evaluación de las predicciones
# ------------------------

# Realizar las predicciones sobre el conjunto de prueba
predictions = model.predict(x_test_f)

# Contador para aciertos
correct_predictions = 0
total_predictions = len(x_test_f)

# Mostrar las primeras 10 imágenes y sus predicciones
for i in range(10):
    plt.imshow(x_test_f[i])  # Mostrar la imagen
    # Obtener la clase predicha (índice máximo de la predicción)
    predicted_class_index = np.argmax(predictions[i])
    # Obtener la clase real (índice máximo de la etiqueta real)
    true_class_index = np.argmax(y_test_f[i])

    # Verificar si la predicción es correcta
    is_correct = "Correcto" if predicted_class_index == true_class_index else "Incorrecto"

    # Si la predicción es correcta, incrementar el contador
    if predicted_class_index == true_class_index:
        correct_predictions += 1

    # Usamos los índices para acceder directamente a las etiquetas
    plt.title(f"Real: {labels[true_class_index]}\nPredicción: {labels[predicted_class_index]}\n{is_correct}")
    plt.axis('off')  # Ocultar los ejes
    plt.show()

# Calcular el porcentaje de aciertos
accuracy_percentage = (correct_predictions / total_predictions) * 100
print(f"Porcentaje de aciertos: {accuracy_percentage:.2f}%")

# Importar librerías necesarias
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# ------------------------
# 1. Cargar y filtrar el dataset
# ------------------------

# Cargar el dataset CIFAR-10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Clases seleccionadas: airplane (0), automobile (1), truck (9)
selected_classes = [0, 1, 9]
labels = ['airplane', 'automobile', 'truck']

# Función para filtrar las clases seleccionadas
def filter_classes(x, y, classes):
    idx = np.isin(y, classes).flatten()  # Filtrar las clases seleccionadas
    x_filtered = x[idx]
    y_filtered = y[idx]
    y_mapped = np.array([classes.index(label[0]) for label in y_filtered])  # Mapeo de etiquetas
    return x_filtered, to_categorical(y_mapped, num_classes=3)

# Filtrar las clases en los conjuntos de entrenamiento y prueba
x_train_f, y_train_f = filter_classes(x_train, y_train, selected_classes)
x_test_f, y_test_f = filter_classes(x_test, y_test, selected_classes)

# Normalizar las imágenes
x_train_f = x_train_f.astype('float32') / 255
x_test_f = x_test_f.astype('float32') / 255

# ------------------------
# 2. Crear el modelo
# ------------------------

# Crear un modelo secuencial
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),  # Capa convolucional
    MaxPooling2D((2, 2)),  # Capa de max pooling
    Conv2D(64, (3, 3), activation='relu'),  # Otra capa convolucional
    MaxPooling2D((2, 2)),  # Otra capa de max pooling
    Flatten(),  # Aplanar la salida para pasarla a la capa densa
    Dense(64, activation='relu'),  # Capa densa con 64 neuronas
    Dense(3, activation='softmax')  # Capa de salida con 3 clases
])

# ------------------------
# 3. Compilar y entrenar el modelo
# ------------------------

# Compilar el modelo con el optimizador 'adam' y la función de pérdida 'categorical_crossentropy'
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
model.fit(x_train_f, y_train_f, epochs=15, batch_size=64, validation_data=(x_test_f, y_test_f))

# ------------------------
# 4. Evaluación de las predicciones
# ------------------------

# Realizar las predicciones sobre el conjunto de prueba
predictions = model.predict(x_test_f)

# Contador para aciertos
correct_predictions = 0
total_predictions = len(x_test_f)

# Mostrar las primeras 10 imágenes y sus predicciones
for i in range(10):
    plt.imshow(x_test_f[i])  # Mostrar la imagen
    # Obtener la clase predicha (índice máximo de la predicción)
    predicted_class_index = np.argmax(predictions[i])
    # Obtener la clase real (índice máximo de la etiqueta real)
    true_class_index = np.argmax(y_test_f[i])

    # Verificar si la predicción es correcta
    is_correct = "Correcto" if predicted_class_index == true_class_index else "Incorrecto"

    # Si la predicción es correcta, incrementar el contador
    if predicted_class_index == true_class_index:
        correct_predictions += 1

    # Usamos los índices para acceder directamente a las etiquetas
    plt.title(f"Real: {labels[true_class_index]}\nPredicción: {labels[predicted_class_index]}\n{is_correct}")
    plt.axis('off')  # Ocultar los ejes
    plt.show()

# Calcular el porcentaje de aciertos
accuracy_percentage = (correct_predictions / total_predictions) * 100
print(f"Porcentaje de aciertos: {accuracy_percentage:.2f}%")