# -*- coding: utf-8 -*-
"""EjercicioEnClase_Taller2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P10f93nCGDZiuqSoQDyvqqpDmk-uZ3ba
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np

# Cargar el dataset completo
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Convertimos etiquetas a 1D
y_train = y_train.flatten()
y_test = y_test.flatten()

# Elegimos solo 3 clases
selected_classes = [1, 8, 9]  # automobile, ship, truck

# Creamos máscaras para quedarnos solo con esas clases
train_mask = np.isin(y_train, selected_classes)
test_mask = np.isin(y_test, selected_classes)

x_train = x_train[train_mask]
y_train = y_train[train_mask]
x_test = x_test[test_mask]
y_test = y_test[test_mask]

# Reasignamos etiquetas a 0, 1 y 2
class_map = {1: 0, 8: 1, 9: 2}
y_train = np.array([class_map[y] for y in y_train])
y_test = np.array([class_map[y] for y in y_test])

# 1. Normalizar imágenes (de 0-255 a 0-1)
x_train = x_train / 255.0
x_test = x_test / 255.0

# 2. Asegurarnos que las etiquetas sean tipo int
y_train = y_train.astype(np.int32)
y_test = y_test.astype(np.int32)

# 3. Crear conjunto de validación (20% del entrenamiento)
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(
    x_train, y_train, test_size=0.2, random_state=42, stratify=y_train
)

# Mostramos forma de los datos
print("x_train:", x_train.shape)
print("x_val:", x_val.shape)
print("x_test:", x_test.shape)

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(3, activation='softmax')  # 3 clases
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train, y_train,
    epochs=10,             # puedes aumentar a 20 o más si quieres
    batch_size=32,
    validation_data=(x_val, y_val)
)





# Gráfica de accuracy y loss
plt.figure(figsize=(12, 4))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Entrenamiento')
plt.plot(history.history['val_accuracy'], label='Validación')
plt.title('Precisión')
plt.xlabel('Épocas')
plt.ylabel('Precisión')
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Entrenamiento')
plt.plot(history.history['val_loss'], label='Validación')
plt.title('Pérdida')
plt.xlabel('Épocas')
plt.ylabel('Pérdida')
plt.legend()

plt.show()

test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=2)
print(f'\n🔍 Precisión en test: {test_accuracy:.4f}')

# Clases que usamos
class_names = ['automobile', 'ship', 'truck']

# Tomamos 3 imágenes del test aleatorias
indices = np.random.choice(len(x_test), 3, replace=False)
sample_images = x_test[indices]
sample_labels = y_test[indices]

# Hacemos predicciones
predictions = model.predict(sample_images)
predicted_classes = np.argmax(predictions, axis=1)

# Mostrar imágenes y predicciones
plt.figure(figsize=(10, 3))
for i in range(3):
    plt.subplot(1, 3, i + 1)
    plt.imshow(sample_images[i])
    plt.axis('off')
    true_label = class_names[sample_labels[i]]
    predicted_label = class_names[predicted_classes[i]]
    color = "green" if predicted_label == true_label else "red"
    plt.title(f"Real: {true_label}\nPred: {predicted_label}", color=color)
plt.tight_layout()
plt.show()