# -*- coding: utf-8 -*-
"""EspectogramaOndaIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGgHQHjcMewhEZzhuJ5slc774YLudHIZ
"""

from google.colab import files
uploaded = files.upload()

# Instalar librosa (si no está instalada aún)
!pip install librosa

# Importar librerías necesarias
import librosa
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io

# Subir archivo de audio
uploaded = files.upload()
filename = list(uploaded.keys())[0]
audio, sr = librosa.load(io.BytesIO(uploaded[filename]), sr=None)

# 1. Tono (Pitch)
pitches, magnitudes = librosa.piptrack(y=audio, sr=sr)
index = magnitudes.argmax()
freq_idx, time_idx = np.unravel_index(index, magnitudes.shape)
pitch = pitches[freq_idx, time_idx]
print('🎵 Tono (Pitch):', pitch)

# 2. Intensidad (Volumen)
rms = librosa.feature.rms(y=audio)
print('📢 Intensidad promedio:', rms.mean())

# 3. Timbre (MFCC)
mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)
print('🎶 Coeficientes MFCC (forma):', mfcc.shape)

# 4. Duración
duration = librosa.get_duration(y=audio, sr=sr)
print('⏱️ Duración:', duration, 'segundos')

# 5. Espectro Armónico (FFT)
fft_result = np.fft.fft(audio)
frequencies = np.fft.fftfreq(len(fft_result), 1/sr)
print('📈 Primeras frecuencias FFT:', frequencies[:10])

# 6. Envolvente Temporal (Forma de Onda)
plt.figure(figsize=(10, 4))
plt.plot(audio)
plt.title('🖋️ Forma de Onda')
plt.xlabel('Tiempo (muestras)')
plt.ylabel('Amplitud')
plt.grid(True)
plt.tight_layout()
plt.show()

# 7. Espectrograma
plt.figure(figsize=(10, 4))
D = librosa.amplitude_to_db(np.abs(librosa.stft(audio)), ref=np.max)
librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log')
plt.colorbar(format='%+2.0f dB')
plt.title('🎨 Espectrograma (escala log)')
plt.tight_layout()
plt.show()

# 8. Visualización de MFCCs
plt.figure(figsize=(10, 4))
librosa.display.specshow(mfcc, x_axis='time', sr=sr)
plt.colorbar()
plt.title('🔍 MFCCs')
plt.tight_layout()
plt.show()