# -*- coding: utf-8 -*-
"""GatovsPerro_Clasificador_CNN_tf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJlscbdDiFOO2j1cfnQm2-2o11fo2xJ8
"""

import tensorflow as tf
import tensorflow_datasets as tfds

datos, metadatos = tfds.load("cats_vs_dogs", as_supervised=True, with_info=True)

tfds.show_examples(datos["train"], metadatos)

import matplotlib.pyplot as plt
import cv2 #opencv - trabajar y hacer trnasformaciones en imagenes

plt.figure(figsize=(20,20))

TAMANO_IMG=100

for i, (imagen, etiqueta) in enumerate(datos["train"].take(25)):
  imagen = cv2.resize(imagen.numpy(), (TAMANO_IMG, TAMANO_IMG))
  imagen = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
  plt.subplot(5, 5, i+1)
  plt.imshow(imagen, cmap="gray")

datos_entrenamiento = []

for i, (imagen, etiqueta) in enumerate(datos["train"]):
  imagen = cv2.resize(imagen.numpy(), (TAMANO_IMG, TAMANO_IMG))
  imagen = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
  imagen = imagen.reshape(TAMANO_IMG, TAMANO_IMG, 1)
  datos_entrenamiento.append([imagen, etiqueta])

datos_entrenamiento[0]

X = []
y = []

for imagen, etiqueta in datos_entrenamiento:
  X.append(imagen)
  y.append(etiqueta)

#Normalizar las imagenes
import numpy as np

X = np.array(X).astype(float) / 255

X[0]

y

y = np.array(y)

modelo = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation="relu", input_shape=(100, 100, 1)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3,3), activation="relu"),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(128, (3,3), activation="relu"),
    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

modelo.compile(
    optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"]
)

modelo.fit(
    X, y, batch_size=32, validation_split=0.15, epochs=50
)

"""Probando ando...
Para comprobar que efectivamente mi modelo puede clasificar si es gato o perro:
"""

from google.colab import files

# Subir imágenes
imagenes_subidas = files.upload()

TAMANO_IMG = 100  # Asegúrate de que esté definido igual que antes

imagenes_prueba = []
nombres = []

for nombre_archivo in imagenes_subidas.keys():
    img = cv2.imread(nombre_archivo)
    img = cv2.resize(img, (TAMANO_IMG, TAMANO_IMG))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape(TAMANO_IMG, TAMANO_IMG, 1)
    img = img.astype("float32") / 255

    imagenes_prueba.append(img)
    nombres.append(nombre_archivo)

imagenes_prueba = np.array(imagenes_prueba)
predicciones = modelo.predict(imagenes_prueba)

import matplotlib.pyplot as plt

etiquetas = ["Gato", "Perro"]

plt.figure(figsize=(10, 5))

for i in range(len(imagenes_prueba)):
    plt.subplot(1, 4, i + 1)
    plt.imshow(imagenes_prueba[i].reshape(TAMANO_IMG, TAMANO_IMG), cmap="gray")
    plt.axis("off")

    clase = 1 if predicciones[i] >= 0.5 else 0
    prob = predicciones[i][0]
    plt.title(f"{etiquetas[clase]}\nConfianza: {prob:.2f}\n({nombres[i]})")

etiquetas = ["Gato", "Perro"]

for i in range(len(imagenes_prueba)):
    clase = 1 if predicciones[i] >= 0.5 else 0
    prob = predicciones[i][0]
    print(f"{nombres[i]} → {etiquetas[clase]} con {prob * 100:.2f}% de confianza")

"""Al principio me confundí un poco, porque cuando el modelo predecía una imagen de gato, salía algo como “Gato con 0% de confianza”, lo cual parecía incorrecto.
El modelo usa una función sigmoid al final, lo que significa que la salida siempre será un valor entre 0 y 1, interpretado como la probabilidad de que la imagen sea un perro (porque los perros son la clase 1 y los gatos la clase 0).

Entonces:

Si el número que da es cercano a 1, el modelo cree que es un perro con alta confianza.

Si el número es cercano a 0, cree que es un gato con alta confianza.
"""

archivo = "gato1.jpg"  # o "perro1.jpg"

img = cv2.imread(archivo)
img = cv2.resize(img, (100, 100))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = img.reshape(-1, 100, 100, 1).astype("float32") / 255.0

prediccion = modelo.predict(img)[0][0]
etiqueta = "Perro" if prediccion >= 0.5 else "Gato"
confianza = prediccion * 100 if etiqueta == "Perro" else (1 - prediccion) * 100

print(f"{archivo} → {etiqueta} con {confianza:.2f}% de confianza")