# -*- coding: utf-8 -*-
"""INVERSIONES_TRII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKn8c07PxRtKDqxUwX5mPFMedEKUtC66

Historico:
"""

# 1. Instalar librerías
!pip install yfinance pandas matplotlib numpy

# 2. Imports
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 3. Definir las acciones
tickers = {
    "Ecopetrol": "EC",       # Ecopetrol
    "Bancolombia": "CIB",    # Bancolombia
    "Cemargos": "CMTOY",     # Cementos Argos
    "Grupo Aval": "AVAL"     # Grupo Aval
}

# 4. Descargar datos históricos (últimos 5 años)
data = yf.download(list(tickers.values()), start="2020-01-01")["Close"]
data = data.rename(columns={v:k for k,v in tickers.items()})

# 5. Retornos mensuales
monthly = data.resample("M").last().pct_change().dropna()

# 6. Simulación de portafolios aleatorios
n_portfolios = 20000
results = np.zeros((3, n_portfolios))
weights_record = []

for i in range(n_portfolios):
    weights = np.random.random(len(monthly.columns))
    weights /= np.sum(weights)

    port_return = np.dot(weights, monthly.mean())*12
    port_vol = np.sqrt(np.dot(weights.T, np.dot(monthly.cov()*12, weights)))
    sharpe = port_return / port_vol

    results[0,i] = port_return
    results[1,i] = port_vol
    results[2,i] = sharpe
    weights_record.append(weights)

# 7. Portafolio óptimo (máx. Sharpe)
max_sharpe_idx = results[2].argmax()
max_sharpe_weights = weights_record[max_sharpe_idx]

# 8. Resultados
print("📈 Portafolio Óptimo (máxima relación Rendimiento/Riesgo)\n")
for asset, w in zip(monthly.columns, max_sharpe_weights):
    print(f"{asset}: {round(w*100,2)}%")

print("\nRendimiento Anual Esperado:", round(results[0,max_sharpe_idx]*100,2), "%")
print("Riesgo (Volatilidad Anual):", round(results[1,max_sharpe_idx]*100,2), "%")

# 9. Gráfico
plt.figure(figsize=(10,6))
plt.scatter(results[1,:], results[0,:], c=results[2,:], cmap="viridis", s=5)
plt.colorbar(label="Sharpe Ratio")
plt.scatter(results[1,max_sharpe_idx], results[0,max_sharpe_idx], c="red", s=100, label="Óptimo")
plt.xlabel("Riesgo (Volatilidad Anual)")
plt.ylabel("Rendimiento Esperado Anual")
plt.title("Frontera Eficiente de Portafolio (Markowitz)")
plt.legend()
plt.show()

"""Lo que se viene:

Moderada):

20% Colombia

60% ETFs globales (SP500, Nasdaq, emergentes)

20% Bonos

Aca simulamos con 1'000.000 COP.
A un tiempo de 5 años.
"""

# 1. Instalar librerías
!pip install yfinance pandas numpy matplotlib

# 2. Imports
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 3. Definir activos
tickers = {
    "Ecopetrol": "EC",        # Acción local
    "Bancolombia": "CIB",
    "Cemargos": "CMTOY",
    "SP500": "SPY",           # ETF S&P500
    "Nasdaq": "QQQ",          # ETF Nasdaq
    "Emergentes": "EEM",      # ETF mercados emergentes
    "Bonos_USA": "BND"        # ETF bonos globales/USA
}

# 4. Descargar 10 años de historia
data = yf.download(list(tickers.values()), start="2013-01-01")["Close"]
data = data.rename(columns={v:k for k,v in tickers.items()})

# 5. Retornos mensuales (históricos)
monthly = data.resample("M").last().pct_change().dropna()

# 6. Estimaciones de retorno y riesgo
mean_returns = monthly.mean()*12   # anualizado
cov_matrix = monthly.cov()*12      # covarianza anual

print("📊 Retornos esperados anuales (%):\n")
print((mean_returns*100).round(2))

# 7. Simular portafolio diversificado
weights = {
    "Ecopetrol": 0.05,
    "Bancolombia": 0.10,
    "Cemargos": 0.05,
    "SP500": 0.25,
    "Nasdaq": 0.25,
    "Emergentes": 0.10,
    "Bonos_USA": 0.20
}

w = np.array([weights[a] for a in mean_returns.index])

expected_return = np.dot(w, mean_returns)
expected_vol = np.sqrt(np.dot(w.T, np.dot(cov_matrix, w)))

print("\n✅ Portafolio Diversificado")
print("Rendimiento Anual Esperado:", round(expected_return*100,2), "%")
print("Volatilidad Anual Estimada:", round(expected_vol*100,2), "%")

# 8. Simulación de inversión inicial (1 millón COP)
capital_inicial = 1_000_000
horizonte = 5  # años
simulaciones = 10000

final_values = []
rng = np.random.default_rng(42)

for _ in range(simulaciones):
    growth = 1
    for year in range(horizonte):
        # simulación Monte Carlo (rendimiento ~ normal)
        rnd = rng.normal(expected_return, expected_vol)
        growth *= (1 + rnd)
    final_values.append(capital_inicial * growth)

# 9. Resultados de simulación
final_values = np.array(final_values)
p50 = np.percentile(final_values, 50)  # mediana
p10 = np.percentile(final_values, 10)  # escenario pesimista
p90 = np.percentile(final_values, 90)  # escenario optimista

print(f"\n💰 Simulación a {horizonte} años con 1M COP:")
print("Escenario Pesimista (10% peor):", round(p10,0), "COP")
print("Escenario Medio (50%):", round(p50,0), "COP")
print("Escenario Optimista (10% mejor):", round(p90,0), "COP")

# 10. Histograma
plt.hist(final_values, bins=50, color="skyblue", edgecolor="black")
plt.axvline(p10, color="red", linestyle="--", label="Pesimista")
plt.axvline(p50, color="blue", linestyle="--", label="Medio")
plt.axvline(p90, color="green", linestyle="--", label="Optimista")
plt.title(f"Distribución del valor futuro en {horizonte} años")
plt.xlabel("Valor final (COP)")
plt.ylabel("Frecuencia")
plt.legend()
plt.show()

"""Comparativa entre
el anterior y algo mas conservador:

"""

# 1. Instalar librerías
!pip install yfinance pandas numpy matplotlib

# 2. Imports
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 3. Definir activos
tickers = {
    "Ecopetrol": "EC",        # Acción local
    "Bancolombia": "CIB",
    "Cemargos": "CMTOY",
    "SP500": "SPY",           # ETF S&P500
    "Nasdaq": "QQQ",          # ETF Nasdaq
    "Emergentes": "EEM",      # ETF mercados emergentes
    "Bonos_USA": "BND"        # ETF bonos USA/global
}

# 4. Descargar 10 años de datos
data = yf.download(list(tickers.values()), start="2013-01-01")["Close"]
data = data.rename(columns={v:k for k,v in tickers.items()})

# 5. Retornos mensuales
monthly = data.resample("M").last().pct_change().dropna()

# 6. Estadísticas
mean_returns = monthly.mean()*12   # anualizados
cov_matrix = monthly.cov()*12

print("📊 Retornos esperados anuales (%):\n")
print((mean_returns*100).round(2))

# 7. Definir portafolios
weights_moderado = {
    "Ecopetrol": 0.05,
    "Bancolombia": 0.10,
    "Cemargos": 0.05,
    "SP500": 0.25,
    "Nasdaq": 0.25,
    "Emergentes": 0.10,
    "Bonos_USA": 0.20
}

weights_conservador = {
    "Ecopetrol": 0.05,
    "Bancolombia": 0.10,
    "Cemargos": 0.05,
    "SP500": 0.20,
    "Nasdaq": 0.20,
    "Emergentes": 0.10,
    "Bonos_USA": 0.40
}

# 8. Función de simulación Monte Carlo
def simular_portafolio(weights, mean_returns, cov_matrix, capital=1_000_000, years=5, sims=10000):
    w = np.array([weights[a] for a in mean_returns.index])
    exp_return = np.dot(w, mean_returns)
    exp_vol = np.sqrt(np.dot(w.T, np.dot(cov_matrix, w)))

    final_values = []
    rng = np.random.default_rng(42)
    for _ in range(sims):
        growth = 1
        for year in range(years):
            rnd = rng.normal(exp_return, exp_vol)
            growth *= (1 + rnd)
        final_values.append(capital * growth)

    final_values = np.array(final_values)
    return {
        "Rendimiento Esperado": round(exp_return*100,2),
        "Volatilidad": round(exp_vol*100,2),
        "P10": round(np.percentile(final_values,10),0),
        "P50": round(np.percentile(final_values,50),0),
        "P90": round(np.percentile(final_values,90),0),
        "Distribucion": final_values
    }

# 9. Correr simulaciones
res_mod = simular_portafolio(weights_moderado, mean_returns, cov_matrix)
res_cons = simular_portafolio(weights_conservador, mean_returns, cov_matrix)

print("\n✅ Portafolio Moderado")
print(res_mod)

print("\n✅ Portafolio Conservador")
print(res_cons)

# 10. Graficar distribuciones
plt.figure(figsize=(10,6))
plt.hist(res_mod["Distribucion"], bins=50, alpha=0.6, label="Moderado", color="skyblue")
plt.hist(res_cons["Distribucion"], bins=50, alpha=0.6, label="Conservador", color="orange")
plt.axvline(res_mod["P50"], color="blue", linestyle="--", label="Mediana Moderado")
plt.axvline(res_cons["P50"], color="red", linestyle="--", label="Mediana Conservador")
plt.title("Distribución de valor final en 5 años (1M COP inicial)")
plt.xlabel("Valor final (COP)")
plt.ylabel("Frecuencia")
plt.legend()
plt.show()

"""Para simular interes compuesto lo subi a 10 años el mimo millon:

"""

# --- Simulación a 10 años con mismos portafolios ---

# 1. Función adaptada a un horizonte flexible
def simular_portafolio(weights, mean_returns, cov_matrix, capital=1_000_000, years=10, sims=10000):
    w = np.array([weights[a] for a in mean_returns.index])
    exp_return = np.dot(w, mean_returns)
    exp_vol = np.sqrt(np.dot(w.T, np.dot(cov_matrix, w)))

    final_values = []
    rng = np.random.default_rng(42)
    for _ in range(sims):
        growth = 1
        for year in range(years):
            rnd = rng.normal(exp_return, exp_vol)
            growth *= (1 + rnd)
        final_values.append(capital * growth)

    final_values = np.array(final_values)
    return {
        "Rendimiento Esperado": round(exp_return*100,2),
        "Volatilidad": round(exp_vol*100,2),
        "P10": round(np.percentile(final_values,10),0),
        "P50": round(np.percentile(final_values,50),0),
        "P90": round(np.percentile(final_values,90),0),
        "Distribucion": final_values
    }

# 2. Simulaciones para 10 años
res_mod_10 = simular_portafolio(weights_moderado, mean_returns, cov_matrix, years=10)
res_cons_10 = simular_portafolio(weights_conservador, mean_returns, cov_matrix, years=10)

print("\n✅ Portafolio Moderado (10 años)")
print(res_mod_10)

print("\n✅ Portafolio Conservador (10 años)")
print(res_cons_10)

# 3. Graficar distribuciones
plt.figure(figsize=(10,6))
plt.hist(res_mod_10["Distribucion"], bins=60, alpha=0.6, label="Moderado", color="skyblue")
plt.hist(res_cons_10["Distribucion"], bins=60, alpha=0.6, label="Conservador", color="orange")
plt.axvline(res_mod_10["P50"], color="blue", linestyle="--", label="Mediana Moderado")
plt.axvline(res_cons_10["P50"], color="red", linestyle="--", label="Mediana Conservador")
plt.title("Distribución de valor final en 10 años (1M COP inicial)")
plt.xlabel("Valor final (COP)")
plt.ylabel("Frecuencia")
plt.legend()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --- Parámetros ---
capital_inicial = 1_000_000        # aporte inicial
aporte_mensual = 500_000           # aporte mensual
anios = 10                         # horizonte
meses = anios * 12

# Función para calcular proyección con aportes mensuales
def proyeccion_con_aportes(r_anual, capital_inicial, aporte_mensual, meses):
    r_mensual = (1 + r_anual) ** (1/12) - 1
    valores = []
    saldo = capital_inicial
    for m in range(meses+1):
        if m > 0:
            saldo = saldo*(1 + r_mensual) + aporte_mensual
        valores.append(saldo)
    return np.array(valores)

# Retorno esperado moderado y conservador
r_mod = retorno_portafolio(weights_moderado)   # ya definido antes
r_con = retorno_portafolio(weights_conservador)

# Proyección mes a mes
val_mod = proyeccion_con_aportes(r_mod, capital_inicial, aporte_mensual, meses)
val_con = proyeccion_con_aportes(r_con, capital_inicial, aporte_mensual, meses)

# Convertir a tabla año por año
anos = np.arange(0, anios+1)
tabla = pd.DataFrame({
    "Año": anos,
    "Moderado (COP)": val_mod[::12].round(0).astype(int),
    "Conservador (COP)": val_con[::12].round(0).astype(int),
})
print("📊 Proyección con 1M inicial + 500k COP mensuales\n")
display(tabla.style.format({"Moderado (COP)": "{:,.0f}", "Conservador (COP)": "{:,.0f}"}))


# Gráfico
plt.figure(figsize=(9,5))
plt.plot(np.arange(meses+1)/12, val_mod, label=f"Moderado ({r_mod*100:.2f}% esperado)")
plt.plot(np.arange(meses+1)/12, val_con, label=f"Conservador ({r_con*100:.2f}% esperado)")
plt.title("Proyección con aportes de 500k mensuales (1M inicial)")
plt.xlabel("Años")
plt.ylabel("COP")
plt.legend()
plt.grid(True, alpha=0.25)
plt.show()

# ==========================================
# PROYECCIÓN DE INVERSIONES EN COLAB
# Con 1M inicial + 500k COP mensuales
# Comparando Portafolio Moderado vs Conservador
# ==========================================

# --- Imports ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --- Parámetros ---
capital_inicial = 1_000_000        # aporte inicial
aporte_mensual = 500_000           # aporte mensual
anios = 10                         # horizonte en años

# Rendimientos anuales esperados (ejemplo del análisis anterior)
r_mod = 0.1124   # 11.24% moderado
r_con = 0.0993   # 9.93% conservador

# --- Función para proyección detallada ---
def proyeccion_detallada(r_anual, capital_inicial, aporte_mensual, anios):
    meses = anios * 12
    r_mensual = (1 + r_anual) ** (1/12) - 1
    valores = []
    aportes = []
    saldo = capital_inicial
    for m in range(meses+1):
        if m > 0:
            saldo = saldo*(1 + r_mensual) + aporte_mensual
        valores.append(saldo)
        aportes.append(capital_inicial + aporte_mensual*m)
    return np.array(valores), np.array(aportes)

# --- Calcular proyecciones ---
val_mod, aport_mod = proyeccion_detallada(r_mod, capital_inicial, aporte_mensual, anios)
val_con, aport_con = proyeccion_detallada(r_con, capital_inicial, aporte_mensual, anios)

# --- Crear tabla año a año ---
anos = np.arange(0, anios+1)
tabla_detallada = pd.DataFrame({
    "Año": anos,
    "Aportes Totales (COP)": aport_mod[::12].astype(int),
    "Moderado Final (COP)": val_mod[::12].astype(int),
    "Moderado Rendimiento (COP)": (val_mod[::12]-aport_mod[::12]).astype(int),
    "Conservador Final (COP)": val_con[::12].astype(int),
    "Conservador Rendimiento (COP)": (val_con[::12]-aport_con[::12]).astype(int)
})

print("📊 Proyección con 1M inicial + 500k mensuales (Aportes vs Rendimiento)\n")
display(tabla_detallada.style.format({
    "Aportes Totales (COP)": "{:,.0f}",
    "Moderado Final (COP)": "{:,.0f}",
    "Moderado Rendimiento (COP)": "{:,.0f}",
    "Conservador Final (COP)": "{:,.0f}",
    "Conservador Rendimiento (COP)": "{:,.0f}"
}))

# --- Gráfico comparativo ---
plt.figure(figsize=(10,6))
plt.plot(anos, val_mod[::12], label="Moderado Final", color="blue")
plt.plot(anos, val_con[::12], label="Conservador Final", color="orange")
plt.plot(anos, aport_mod[::12], label="Aportes Totales", color="gray", linestyle="--")
plt.title("Capital Final vs Aportes (1M inicial + 500k mensuales)")
plt.xlabel("Años")
plt.ylabel("COP")
plt.legend()
plt.grid(alpha=0.25)
plt.show()