# -*- coding: utf-8 -*-
"""RubianoJuan_IA_Parcial1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ_jvrufMapGj2PsAB3LXOYvUn1qZPM0
"""

# Importar las librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Generar datos sintéticos para el entrenamiento del modelo
np.random.seed(42)

# Cantidad de muestras
n = 1000

# Crear las columnas del dataset
cantidad_enviada = np.random.randint(1, 100, n)
distancia_envio = np.random.uniform(10, 1000, n)
modo_transporte = np.random.choice([1, 2, 3], n)
fragilidad = np.random.choice([0, 1], n)

# Relación simple para unidades perdidas (fórmula)
unidades_perdidas = (0.05 * cantidad_enviada +
                     0.01 * distancia_envio +
                     2 * (modo_transporte == 3) +
                     3 * fragilidad +
                     np.random.normal(0, 2, n)).astype(int)

# Asegurarse de que las pérdidas no sean negativas
unidades_perdidas = np.clip(unidades_perdidas, 0, None)

# Crear el DataFrame
df = pd.DataFrame({
    'Cantidad enviada': cantidad_enviada,
    'Distancia del envío': distancia_envio,
    'Modo de transporte': modo_transporte,
    'Fragilidad': fragilidad,
    'Unidades perdidas': unidades_perdidas
})

# Mostrar las primeras filas
print(df.head())

# Visualizar un resumen estadístico
print(df.describe())

# Configurar el estilo de los gráficos
plt.style.use('ggplot')

# Gráfico de dispersión: cantidad enviada vs. unidades perdidas
plt.figure(figsize=(8, 5))
plt.scatter(df['Cantidad enviada'], df['Unidades perdidas'], alpha=0.6)
plt.title('Relación entre Cantidad enviada y Unidades perdidas')
plt.xlabel('Cantidad enviada')
plt.ylabel('Unidades perdidas')
plt.show()

# Gráfico de cajas: modo de transporte vs. unidades perdidas
plt.figure(figsize=(8, 5))
sns.boxplot(x='Modo de transporte', y='Unidades perdidas', data=df)
plt.title('Unidades perdidas según el modo de transporte')
plt.xlabel('Modo de transporte (1=Camión, 2=Furgoneta, 3=Avión)')
plt.ylabel('Unidades perdidas')
plt.show()

# Gráfico de barras: fragilidad vs. unidades perdidas
plt.figure(figsize=(8, 5))
sns.barplot(x='Fragilidad', y='Unidades perdidas', data=df)
plt.title('Impacto de la fragilidad en las Unidades perdidas')
plt.xlabel('Fragilidad (0=Baja, 1=Alta)')
plt.ylabel('Unidades perdidas')
plt.show()

# Separar las características (X) y la variable objetivo (y)
X = df[['Cantidad enviada', 'Distancia del envío', 'Modo de transporte', 'Fragilidad']]
y = df['Unidades perdidas']

# Mostrar las primeras filas de X e y para verificar
print("Características (X):")
print(X.head())

print("\nVariable objetivo (y):")
print(y.head())

from sklearn.model_selection import train_test_split

# Dividir los datos en entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Verificar las dimensiones de cada conjunto
print("Tamaño del conjunto de entrenamiento:", X_train.shape)
print("Tamaño del conjunto de prueba:", X_test.shape)

from sklearn.linear_model import LinearRegression

# Crear el modelo
modelo = LinearRegression()

# Entrenar el modelo con los datos de entrenamiento
modelo.fit(X_train, y_train)

# Ver los coeficientes y la intercepción
print("Coeficientes del modelo:", modelo.coef_)
print("Intercepción del modelo:", modelo.intercept_)

"""Nota:La intercepción es -1.92… Esto significa que si todas las variables = 0 (cantidad enviada = 0, distancia = 0, etc.),habría -1.92 pérdidas.
Aunque no tiene sentido perder "productos negativos", esto pasa porque la regresión lineal no siempre tiene restricciones para valores negativos.



"""

#Evaluar el modelo:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Realizar predicciones con el conjunto de prueba
y_pred = modelo.predict(X_test)

# Calcular métricas de evaluación
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Mostrar resultados
print("Error Absoluto Medio (MAE):", mae)
print("Error Cuadrático Medio (MSE):", mse)

# Gráfico de las predicciones vs. los valores reales
plt.figure(figsize=(8, 5))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.title('Predicciones vs. Valores Reales')
plt.xlabel('Valores Reales (y_test)')
plt.ylabel('Predicciones (y_pred)')
plt.show()



"""Después de entrenar un modelo de Regresión Lineal, decidi probar por el Árbol de Decisión, a modo de comparacion, o intentar mejorar las predicciones."""

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Crear el modelo de Árbol de Decisión
modelo_arbol = DecisionTreeRegressor(max_depth=5, random_state=42)

# Entrenar el modelo
modelo_arbol.fit(X_train, y_train)

# Realizar predicciones
y_pred_arbol = modelo_arbol.predict(X_test)

# Calcular métricas
mae_arbol = mean_absolute_error(y_test, y_pred_arbol)
mse_arbol = mean_squared_error(y_test, y_pred_arbol)

# Mostrar resultados
print("Resultados del Árbol de Decisión:")
print("Error Absoluto Medio (MAE):", mae_arbol)
print("Error Cuadrático Medio (MSE):", mse_arbol)

"""El MAE y el MSE son mayores en el Árbol de Decisión, para este caso, la Regresión Lineal predijo con más precisión.
Esto se debe a que los datos sintéticos que creamos siguen patrones lineales, así que un modelo simple como la Regresión Lineal funciona mejor.
"""

# Gráfico de predicciones vs valores reales para el Árbol de Decisión
plt.figure(figsize=(8, 5))
plt.scatter(y_test, y_pred_arbol, color='green', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.title('Árbol de Decisión: Predicciones vs. Valores Reales')
plt.xlabel('Valores Reales (y_test)')
plt.ylabel('Predicciones (y_pred_arbol)')
plt.show()

# Comparación de modelos: Regresión Lineal vs. Árbol de Decisión
resultados = pd.DataFrame({
    'Modelo': ['Regresión Lineal', 'Árbol de Decisión'],
    'MAE': [mae, mae_arbol],
    'MSE': [mse, mse_arbol]
})

print("📊 Comparación de Modelos:")
print(resultados)