# -*- coding: utf-8 -*-
"""TRABAJO_PRÁCTICO_MINERÍA_DE_DATOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOht-myMsjApb_n7bbazTJor5GeejO4E

1.Preparación del entorno.
"""

#Impor librerias necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

"""Ejercicio 2:

2.1 Crear dataset sintético (300 puntos, 3 clústeres)
"""

# Crear dataset con 300 puntos y 3 clusters
X, y = make_blobs(n_samples=300, centers=3, random_state=42)

# Convertir a DataFrame
df = pd.DataFrame(X, columns=['x', 'y'])

# Gráfico en dispersión
plt.scatter(df['x'], df['y'])
plt.title("Datos Sintéticos - Dispersión")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

"""2.2. Aplicar K-Means con k = 3"""

# Crear el modelo
kmeans = KMeans(n_clusters=3, random_state=42)

# Ajustar el modelo
kmeans.fit(df)

# Obtener etiquetas
labels = kmeans.labels_

# Obtener centroides
centroids = kmeans.cluster_centers_

# Graficar clusters coloreados
plt.scatter(df['x'], df['y'], c=labels, cmap='viridis')
plt.scatter(centroids[:, 0], centroids[:, 1], s=200, c='red', marker='X')
plt.title("K-Means con k=3")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

"""2.3. Cambiar K a 4"""

kmeans4 = KMeans(n_clusters=4, random_state=42)
kmeans4.fit(df)

labels4 = kmeans4.labels_
centroids4 = kmeans4.cluster_centers_

plt.scatter(df['x'], df['y'], c=labels4, cmap='rainbow')
plt.scatter(centroids4[:, 0], centroids4[:, 1], s=200, c='black', marker='X')
plt.title("K-Means con k=4")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

"""***2.3. Preguntas de análisis***

**¿Qué representa un centroide?**
El centroide es el punto promedio de todos los datos dentro de un clúster.
Es como decir: "este punto representa el corazón del grupo".

**¿Qué pasa si cambias K a 4? (pruébalo)**
El algoritmo fuerza a crear 4 grupos, aunque los datos originalmente sean 3.
Esto produce un clúster extra que divide uno de los anteriores, incluso si no tiene sentido natural.

**¿El algoritmo requiere saber K antes o lo infiere?**
K-Means requiere que tú le digas el valor de K antes.
No lo infiere automáticamente.
Para buscar el mejor K, normalmente se usa el Método del Codo (Elbow Method)

**EJERCICIO #3:**
3.1. Generar dataset con make_regression()
"""

from sklearn.datasets import make_regression

# Dataset de regresión
X_reg, y_reg = make_regression(
    n_samples=300,
    n_features=1,
    noise=15,
    random_state=42
)

# Convertir a DataFrame
df_reg = pd.DataFrame({'x': X_reg.flatten(), 'y': y_reg})

# Gráfico
plt.scatter(df_reg['x'], df_reg['y'])
plt.title("Datos de Regresión")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

"""**3.2. Dividir en entrenamiento y prueba**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

"""**3.3. Entrenar modelo de regresión**"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Modelo
model = LinearRegression()

# Entrenar
model.fit(X_train, y_train)

# Predicción sobre todo el dataset para graficar la línea
y_pred_all = model.predict(X_reg)

# Graficar línea de regresión
plt.scatter(X_reg, y_reg, label="Datos")
plt.plot(X_reg, y_pred_all, color="red", linewidth=2, label="Regresión")
plt.title("Regresión Lineal")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

# MSE
y_pred_test = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred_test)
mse

"""**Preguntas **

**1) ¿La relación es lineal o no?**

Sí. Se nota porque la nube de puntos sigue una tendencia recta y el modelo encaja una línea que reduce el error.

**2) ¿Qué pasaría si el dataset tuviera más ruido?**

La nube estaría más dispersa y el modelo tendría más dificultad para encontrar una tendencia clara → mayor MSE.

**3) ¿El MSE es alto o bajo?**

Depende del ruido del dataset. Si tu MSE es pequeño comparado con la escala del y, entonces el modelo está capturando bien la tendencia.

**4. Ejercicio 3 – Clasificación con KNN**

**4.1. Crear dataset con make_classification()**
"""

from sklearn.datasets import make_classification

X_clf, y_clf = make_classification(
    n_samples=300,
    n_features=2,
    n_informative=2,   # todas las features informativas
    n_redundant=0,     # ninguna redundante
    n_repeated=0,      # ninguna repetida
    n_classes=2,
    n_clusters_per_class=1,
    random_state=42
)

df_clf = pd.DataFrame({'x1': X_clf[:, 0], 'x2': X_clf[:, 1], 'y': y_clf})

plt.scatter(df_clf['x1'], df_clf['x2'], c=df_clf['y'], cmap='coolwarm')
plt.title("Dataset de Clasificación 2D")
plt.xlabel("x1")
plt.ylabel("x2")
plt.show()

"""**4.2. Entrenar modelo KNN**"""

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Normalizar
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_clf)

# Train/test
Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_scaled, y_clf, test_size=0.2, random_state=42
)

# KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(Xc_train, yc_train)

# Predicción
y_pred_knn = knn.predict(Xc_test)

# Accuracy
accuracy = accuracy_score(yc_test, y_pred_knn)
accuracy

"""**Preguntas**

**1) ¿Qué significa tener ≥85% accuracy?**

Que el modelo clasifica correctamente más del 85% de los ejemplos de prueba.
O sea, toma buenas decisiones con datos nuevos.

**2) ¿Qué pasa si K = 1 o K = 20?**

**K = 1:**
Súper sensible al ruido. Clasifica por el vecino más cercano ,y puede fallar más.

**K = 20:**
Sobreesmoothed. Mezcla demasiados vecinos por ende pierde detalles.

**3) ¿La clasificación predice clases o valores continuos?**
Predice clases.
Si predijera valores continuos, sería regresión.

**5. Ejercicio 4 – Mini actividad ART2**

**Tomar 50 puntos del dataset del clusterin**g
"""

subset = df.iloc[:50].values

"""## Función ART2 básica

> Añadir blockquote


"""

import numpy as np

def asignar_clusters(vigilancia):
    clusters = []

    for punto in subset:
        asignado = False

        # Revisar cada cluster ya creado
        for c in clusters:
            centro = np.mean(c, axis=0)

            # Similitud por coseno
            num = np.dot(punto, centro)
            den = np.linalg.norm(punto) * np.linalg.norm(centro)
            similitud = num / den

            if similitud >= vigilancia:
                c.append(punto)
                asignado = True
                break

        # Si no encontró cluster → crear uno nuevo
        if not asignado:
            clusters.append([punto])

    return clusters

clusters_09 = asignar_clusters(0.9)
clusters_07 = asignar_clusters(0.7)
clusters_04 = asignar_clusters(0.4)

"""**Preguntas**

**1) ¿Con qué valor se crearon más clústeres?**
Con vigilancia = 0.9, porque exige alta similitud → divide más.

**2) ¿Por qué la vigilancia alta divide tanto?**
Porque obliga a que cada punto sea muy parecido al centro del grupo.
Si no lo es, crea un cluster nuevo.

**3) ¿Por qué ART2 es útil para datos dinámicos?**
Porque no necesita K y puede crear nuevos clústeres en tiempo real a medida que llegan datos.
Es adaptativo.
"""